use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - brave
      - google
      - bing

general:
  instance_name: "OrangeBrowse Search"

search:
  safe_search: 1

  formats:
    - html
    - json

server:
  secret_key: "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET"

  limiter: false

  image_proxy: true

  public_instance: false

  bind_address: "0.0.0.0"

engines:

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    disabled: false

  - name: google
    engine: google
    shortcut: go
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false
